const groups={Core:["Command Center"],"Service Operations":["Service Desk","Incidents","Problems","Changes","Releases","SLA / OLA"],Infrastructure:["Monitoring","Assets / CMDB","Network","Servers","Applications","Software"],Resilience:["Backup / DR"],Governance:["Risk / Controls"],Commercial:["Vendors","Finance"],"Planning & Excellence":["Capacity","Automation","Knowledge","Runbooks","SOP","Continual Improvement","Planning","On-Call","Handover","RACI"]};
const sheets={"Command Center":"ITOM Command Center","Service Desk":"Service Desk","Incidents":"Incident Log","Problems":"Problem Management","Changes":"Change Register","Releases":"Release Tracker","SLA / OLA":"SLA Tracker","Monitoring":"Monitoring Events","Assets / CMDB":"Asset Inventory","Network":"Network Inventory","Servers":"Server Inventory","Applications":"Application Inventory","Software":"Software Licenses","Backup / DR":"Backup Tracker","Vendors":"Vendor Contracts","Risk / Controls":"Risk Register","Finance":"IT Cost Tracker","Capacity":"Capacity Planning","Automation":"Automation Tracker","Knowledge":"Knowledge Base","Runbooks":"Runbook Register","SOP":"SOP Tracker","Continual Improvement":"Continuous Improvement","Planning":"Operations Planner","On-Call":"On-Call Schedule","Handover":"Shift Handover","RACI":"RACI Matrix"};
const d={inc:12,p1:2,sla:"97.4%",up:"99.92%",backup:1,change:4,risk:3,cost:"R 186,420"};
let authed=false;
function nav(){let n=document.getElementById("nav");Object.entries(groups).forEach(([g,items])=>{let h=document.createElement("div");h.textContent=g;n.append(h);items.forEach(name=>{let b=document.createElement("button");b.textContent=name;b.onclick=()=>openModule(name);n.append(b)})})}
function k(label,val,sub){return '<div class="card"><small>'+label+'</small><strong>'+val+'</strong><small>'+sub+'</small></div>'}
function openModule(name){if(!authed){showLogin();return}document.getElementById("title").textContent=name;let c=document.getElementById("content");
if(name==="Command Center"){c.innerHTML='<div class="cards">'+k("Open incidents",d.inc,"Active workload")+k("P1 incidents",d.p1,"Critical queue")+k("SLA compliance",d.sla,"Rolling view")+k("Availability",d.up,"Service uptime")+k("Failed backups",d.backup,"Latest state")+k("Changes",d.change,"Scheduled / pending")+k("Critical risks",d.risk,"Open treatments")+k("Monthly IT cost",d.cost,"ZAR operating view")+'</div><div class="grid"><div class="panel"><h3>Operational workload</h3>'+row("Incidents",72,12)+row("Service requests",58,31)+row("Changes",38,4)+row("Problems",26,6)+row("Backups",12,1)+'</div><div class="panel"><h3>Attention queue</h3><table class="table"><tr><th>Item</th><th>Status</th></tr><tr><td>P1 incident INC-1042</td><td><span class="tag">Critical</span></td></tr><tr><td>Backup BR-221</td><td><span class="tag">Failed</span></td></tr><tr><td>Contract V-019</td><td><span class="tag">Renewal due</span></td></tr></table></div></div>'}
else c.innerHTML='<div class="panel"><h3>'+name+'</h3><div class="empty">Web module mapped to Excel source sheet <b>'+sheets[name]+'</b>.<br><br>The public frontend is ready; live CRUD, database persistence, and OAuth enforcement belong in the authenticated backend.</div></div>'}
function row(name,p,val){return '<div class="row"><span>'+name+'</span><div class="bar"><i style="width:'+p+'%"></i></div><span>'+val+'</span></div>'}
function showLogin(){document.getElementById("modal").hidden=false}
function hideLogin(){document.getElementById("modal").hidden=true}
document.getElementById("open").onclick=showLogin;document.getElementById("sign").onclick=()=>authed?setAuth(false):showLogin;document.getElementById("x").onclick=hideLogin;
document.getElementById("oauth").onclick=()=>document.getElementById("msg").innerHTML='<span class="warn">GitHub OAuth needs a server-side callback. Enforce the allowed GitHub username <b>NazeerK</b> on the server; never trust a client-side username or expose an OAuth secret.</span>';
function setAuth(v){authed=v;document.getElementById("public").hidden=v;document.getElementById("workspace").hidden=!v;document.getElementById("auth").textContent=v?"NazeerK · Authorized":"Public Site";document.getElementById("sign").textContent=v?"Sign out":"Sign in";if(v){hideLogin();openModule("Command Center")}}
nav();